/* Espera 11 minutos después de hacer los cambios en tu sitio, para depués
 * actualizar este archivo. */
const CACHE = "gilpgdm-2.00";

/** Archivos requeridos para que la aplicación funcione fuera de línea. */
const ARCHIVOS = [
 "favicon.ico",
 "index.html",
 "LICENSE",
 "print.html",
 "site.webmanifest",
 "sw.html",
 "1_multiplataforma/a_nativa.html",
 "1_multiplataforma/b_multiplataforma.html",
 "1_multiplataforma/c_diferencias.html",
 "1_multiplataforma/d_ventajas_nativas.html",
 "1_multiplataforma/e_desventajas_nativas.html",
 "1_multiplataforma/f_ventajas_multiplataforma.html",
 "1_multiplataforma/g_desventajas_multiplataforma.html",
 "1_multiplataforma/index.html",
 "1_multiplataforma/print.html",
 "1_multiplataforma/cmp/a2-nativa.js",
 "1_multiplataforma/cmp/b2-multiplataforma.js",
 "1_multiplataforma/cmp/c2-diferencias.js",
 "1_multiplataforma/cmp/d2-ventajas-nativas.js",
 "1_multiplataforma/cmp/e2-desventajas-nativas.js",
 "1_multiplataforma/cmp/f2-ventajas-multi.js",
 "1_multiplataforma/cmp/g2-desventajas-multi.js",
 "1_multiplataforma/cmp/nativas-contenido.js",
 "1_multiplataforma/cmp/nativas-index.js",
 "1_multiplataforma/cmp/nativas-print.js",
 "2_multimedia/a_imagenes.html",
 "2_multimedia/b_audio_y_video.html",
 "2_multimedia/c_audio.html",
 "2_multimedia/d_video.html",
 "2_multimedia/index.html",
 "2_multimedia/print.html",
 "2_multimedia/cmp/a2-imagenes.js",
 "2_multimedia/cmp/b2-audio-video.js",
 "2_multimedia/cmp/c2-audio.js",
 "2_multimedia/cmp/d2-video.js",
 "2_multimedia/cmp/multimedia-contenido.js",
 "2_multimedia/cmp/multimedia-index.js",
 "2_multimedia/cmp/multimedia-print.js",
 "2_multimedia/src/2a_imagenes.html",
 "2_multimedia/src/2c_audio.html",
 "2_multimedia/src/2d_video.html",
 "2_multimedia/src/clouds_poster.jpg",
 "3_vistas/a_referencias.html",
 "3_vistas/b_app.html",
 "3_vistas/c_campos.html",
 "3_vistas/d_interruptores.html",
 "3_vistas/e_botones.html",
 "3_vistas/f_navegacion.html",
 "3_vistas/g_gps.html",
 "3_vistas/h_archivos.html",
 "3_vistas/index.html",
 "3_vistas/print.html",
 "3_vistas/cmp/a3-referencias.js",
 "3_vistas/cmp/b3-app.js",
 "3_vistas/cmp/c3-campos.js",
 "3_vistas/cmp/d3-interruptores.js",
 "3_vistas/cmp/e3-botones.js",
 "3_vistas/cmp/f3-navegacion.js",
 "3_vistas/cmp/g3-gps.js",
 "3_vistas/cmp/h3-archivos.js",
 "3_vistas/cmp/vistas-contenido.js",
 "3_vistas/cmp/vistas-index.js",
 "3_vistas/cmp/vistas-print.js",
 "3_vistas/img/app_android.png",
 "3_vistas/img/app_ios.png",
 "3_vistas/img/switch_android.png",
 "3_vistas/img/switch_ios.png",
 "3_vistas/src/3b_app.html",
 "3_vistas/src/3c_campos.html",
 "3_vistas/src/3d_interruptor.html",
 "3_vistas/src/3e_botones.html",
 "3_vistas/src/3f_navegacion.html",
 "3_vistas/src/3g_gps.html",
 "3_vistas/src/3h_archivos.html",
 "4_pwa/a_pwa.html",
 "4_pwa/b_archivos.html",
 "4_pwa/c_ayuda.html",
 "4_pwa/d_index.html",
 "4_pwa/e_CtrlRecomienda.html",
 "4_pwa/f_config.html",
 "4_pwa/g_movil.html",
 "4_pwa/h_mi-nav_js.html",
 "4_pwa/index.html",
 "4_pwa/i_mi-nav_css.html",
 "4_pwa/j_favicon.html",
 "4_pwa/k_icono256.html",
 "4_pwa/l_icono1024.html",
 "4_pwa/m_icono2048.html",
 "4_pwa/n_webmanifest.html",
 "4_pwa/o_sw.html",
 "4_pwa/print.html",
 "4_pwa/p_estilos.html",
 "4_pwa/q_principal.html",
 "4_pwa/r_ripple.html",
 "4_pwa/s_botones.html",
 "4_pwa/t_cmp-din_js.html",
 "4_pwa/u_cmp-din_css.html",
 "4_pwa/v_material-icons.html",
 "4_pwa/w_MaterialIcons-Regular_codepoints.html",
 "4_pwa/x_MaterialIcons-Regular.html",
 "4_pwa/y_LICENSE.html",
 "4_pwa/cmp/a4-pwa.js",
 "4_pwa/cmp/b4-archivos.js",
 "4_pwa/cmp/c4-ayuda.js",
 "4_pwa/cmp/d4-index.js",
 "4_pwa/cmp/e4-ctrl-recomienda.js",
 "4_pwa/cmp/f4-config.js",
 "4_pwa/cmp/g4-movil.js",
 "4_pwa/cmp/h4-mi-nav-js.js",
 "4_pwa/cmp/i4-mi-nav-css.js",
 "4_pwa/cmp/j4-favicon.js",
 "4_pwa/cmp/k4-icono256.js",
 "4_pwa/cmp/l4-icono1024.js",
 "4_pwa/cmp/m4-icono2048.js",
 "4_pwa/cmp/n4-webmanifest.js",
 "4_pwa/cmp/o4-sw.js",
 "4_pwa/cmp/p4-estilos.js",
 "4_pwa/cmp/pwa-contenido.js",
 "4_pwa/cmp/pwa-index.js",
 "4_pwa/cmp/pwa-print.js",
 "4_pwa/cmp/q4-principal.js",
 "4_pwa/cmp/r4-ripple.js",
 "4_pwa/cmp/s4-botones.js",
 "4_pwa/cmp/t4_cmp-din-js.js",
 "4_pwa/cmp/u4-cmp-din-css.js",
 "4_pwa/cmp/v4-material-icons.js",
 "4_pwa/cmp/w4-material-codepoints.js",
 "4_pwa/cmp/x4-material-regular.js",
 "4_pwa/cmp/y4-license.js",
 "4_pwa/img/favicon.ico",
 "4_pwa/img/icono1024.png",
 "4_pwa/img/icono2048.png",
 "4_pwa/img/icono256.png",
 "4_pwa/src/LICENSE.html",
 "4_pwa/src/MaterialIcons-Regular.codepoints",
 "4_pwa/src/MaterialIcons-Regular.ttf",
 "4_pwa/src/pwa.zip",
 "5_sesion/a_arquitectura.html",
 "5_sesion/b_despliegue.html",
 "5_sesion/c_er.html",
 "5_sesion/d_instrucciones.html",
 "5_sesion/e_archivos.html",
 "5_sesion/f_index_html.html",
 "5_sesion/g_CtrlSesion.html",
 "5_sesion/h_index_js.html",
 "5_sesion/index.html",
 "5_sesion/i_validaUsuario.html",
 "5_sesion/j_LICENSE.html",
 "5_sesion/print.html",
 "5_sesion/cmp/a5-arquitectura.js",
 "5_sesion/cmp/b5-despliegue.js",
 "5_sesion/cmp/c5-er.js",
 "5_sesion/cmp/d5-instrucciones.js",
 "5_sesion/cmp/e5-archivos.js",
 "5_sesion/cmp/f5-index-html.js",
 "5_sesion/cmp/g5-ctrl-sesion.js",
 "5_sesion/cmp/h5-index-js.js",
 "5_sesion/cmp/i5-valida-usuario.js",
 "5_sesion/cmp/j5-license.js",
 "5_sesion/cmp/sesion-contenido.js",
 "5_sesion/cmp/sesion-index.js",
 "5_sesion/cmp/sesion-print.js",
 "5_sesion/img/aut_componentes.svg",
 "5_sesion/img/aut_despliegue.svg",
 "5_sesion/img/aut_entidades.svg",
 "5_sesion/img/icono2048.png",
 "5_sesion/src/LICENSE.html",
 "6_iot/a_casos.html",
 "6_iot/b_despliegue.html",
 "6_iot/c_er.html",
 "6_iot/d_no_rel.html",
 "6_iot/e_instrucciones.html",
 "6_iot/f_archivos.html",
 "6_iot/g_tipos.html",
 "6_iot/h_cliente.html",
 "6_iot/index.html",
 "6_iot/i_getValor.html",
 "6_iot/j_setValor.html",
 "6_iot/k_index_js.html",
 "6_iot/l_index_html.html",
 "6_iot/print.html",
 "6_iot/cmp/a6-casos.js",
 "6_iot/cmp/b6-despliegue.js",
 "6_iot/cmp/c6-er.js",
 "6_iot/cmp/d6-no-rel.js",
 "6_iot/cmp/e6-instrucciones.js",
 "6_iot/cmp/f6-archivos.js",
 "6_iot/cmp/g6-tipos.js",
 "6_iot/cmp/h6-cliente.js",
 "6_iot/cmp/i6-get-valor.js",
 "6_iot/cmp/iot-contenido.js",
 "6_iot/cmp/iot-index.js",
 "6_iot/cmp/iot-print.js",
 "6_iot/cmp/j6-set-valor.js",
 "6_iot/cmp/k6-index.js",
 "6_iot/cmp/l6-index-html.js",
 "6_iot/img/casos_iot.svg",
 "6_iot/img/despliegue_iot.svg",
 "6_iot/img/entidades_iot.svg",
 "6_iot/img/nosql_iot.svg",
 "7_esp8266/a_blink.html",
 "7_esp8266/b_button.html",
 "7_esp8266/c_Dispositivo.html",
 "7_esp8266/index.html",
 "7_esp8266/print.html",
 "7_esp8266/cmp/a7-blink.js",
 "7_esp8266/cmp/b7-button.js",
 "7_esp8266/cmp/c7-dispositivo.js",
 "7_esp8266/cmp/esp8266-contenido.js",
 "7_esp8266/cmp/esp8266-index.js",
 "7_esp8266/cmp/esp8266-print.js",
 "7_esp8266/img/dispositivo.gif",
 "7_esp8266/img/Video-Blink.gif",
 "7_esp8266/img/Video-Button.gif",
 "cmp/gilpgdm-index.js",
 "cmp/gilpgdm-print.js",
 "cmp/mi-nav.js",
 "cmp/sw-index.js",
 "css/estilos.css",
 "img/80x15.png",
 "img/icono1024.png",
 "img/icono2048.png",
 "img/icono256.png",
 "js/config.js",
 "lib/Diapositiva.js",
 "lib/layout-cajon.js",
 "lib/layout-cajon_shadow.js",
 "lib/mi-footer.js",
 "lib/muestra-codigo.js",
 "lib/muestra-codigo_shadow.js",
 "lib/utilHtml.js",
 "lib/css/estilos.css",
 "lib/css/gentium-book-basic-v11-latin-700.woff",
 "lib/css/gentium-book-basic-v11-latin-700.woff2",
 "lib/css/gentium-book-basic-v11-latin-700italic.woff",
 "lib/css/gentium-book-basic-v11-latin-700italic.woff2",
 "lib/css/gentium-book-basic-v11-latin-italic.woff",
 "lib/css/gentium-book-basic-v11-latin-italic.woff2",
 "lib/css/gentium-book-basic-v11-latin-regular.woff",
 "lib/css/gentium-book-basic-v11-latin-regular.woff2",
 "lib/css/gentium-book-basic.css",
 "lib/css/material-icons.css",
 "lib/css/MaterialIcons-Regular.codepoints",
 "lib/css/MaterialIcons-Regular.ttf",
 "lib/css/mi-footer.css",
 "lib/css/prueba.css",
 "lib/css/ubuntu-mono-v10-latin-700.woff",
 "lib/css/ubuntu-mono-v10-latin-700.woff2",
 "lib/css/ubuntu-mono-v10-latin-700italic.woff",
 "lib/css/ubuntu-mono-v10-latin-700italic.woff2",
 "lib/css/ubuntu-mono-v10-latin-italic.woff",
 "lib/css/ubuntu-mono-v10-latin-italic.woff2",
 "lib/css/ubuntu-mono-v10-latin-regular.woff",
 "lib/css/ubuntu-mono-v10-latin-regular.woff2",
 "lib/css/ubuntu-mono.css",
 "lib/css/ubuntu-v15-latin-700.woff",
 "lib/css/ubuntu-v15-latin-700.woff2",
 "lib/css/ubuntu-v15-latin-700italic.woff",
 "lib/css/ubuntu-v15-latin-700italic.woff2",
 "lib/css/ubuntu-v15-latin-italic.woff",
 "lib/css/ubuntu-v15-latin-italic.woff2",
 "lib/css/ubuntu-v15-latin-regular.woff",
 "lib/css/ubuntu-v15-latin-regular.woff2",
 "lib/css/ubuntu.css",
 "/"
];

addEventListener("install", evt => {
 console.log("Service Worker instalado.");
 // @ts-ignore
 evt.waitUntil(cargaCache());
});

addEventListener("fetch", evt => {
 // @ts-ignore
 if (evt.request.method === "GET") {
  // @ts-ignore
  evt.respondWith(usaCache(evt));
 }
});

addEventListener("activate", () => console.log("Service Worker activo."));

async function cargaCache() {
 console.log("Intentando cargar cache: " + CACHE);
 const cache = await caches.open(CACHE);
 await cache.addAll(ARCHIVOS);
 console.log("Cache cargado: " + CACHE);
}

async function usaCache(evt) {
 const cache = await caches.open(CACHE);
 const response = await cache.match(evt.request, { ignoreSearch: true });
 if (response) {
  return response;
 } else {
  return fetch(evt.request);
 }
}