// @ts-nocheck
/* Espera 11 minutos después de hacer los cambios en tu sitio, para depués
 * actualizar este archivo. */
const CACHE = "gilpgdm-1.01";

/**  Archivos requeridos para que la aplicación funcione fuera de línea. */
const ARCHIVOS = [
  "3_multiplataforma/cmp/ctrl-diapositiva.js",
  "3_multiplataforma/cmp/nav-local.js",
  "3_multiplataforma/2_contenido.html",
  "3_multiplataforma/3_nativa.html",
  "3_multiplataforma/4_multiplataforma.html",
  "3_multiplataforma/5_diferencias.html",
  "3_multiplataforma/6_ventajas_nativas.html",
  "3_multiplataforma/7_ventajas_multiplataforma.html",
  "3_multiplataforma/index.html",
  "4_multimedia/cmp/ctrl-diapositiva.js",
  "4_multimedia/cmp/nav-local.js",
  "4_multimedia/src/1_imagenes.html",
  "4_multimedia/src/2_audio.html",
  "4_multimedia/src/3_video.html",
  "4_multimedia/src/bensound-summer.mp3",
  "4_multimedia/src/clouds_poster.jpg",
  "4_multimedia/2_contenido.html",
  "4_multimedia/3_a.html",
  "4_multimedia/4_imagenes.html",
  "4_multimedia/5_ejemplo_imagenes.html",
  "4_multimedia/6_audio_y_video.html",
  "4_multimedia/7_audio.html",
  "4_multimedia/8_ejemplo_audio.html",
  "4_multimedia/9_video.html",
  "4_multimedia/10_ejemplo_video.html",
  "4_multimedia/index.html",
  "5_pwa/cmp/ctrl-diapositiva.js",
  "5_pwa/cmp/nav-local.js",
  "5_pwa/img/favicon.ico",
  "5_pwa/img/icono256.png",
  "5_pwa/img/icono1024.png",
  "5_pwa/img/icono2048.png",
  "5_pwa/src/init.js",
  "5_pwa/src/LICENSE.html",
  "5_pwa/2_contenido.html",
  "5_pwa/3_instrucciones.html",
  "5_pwa/4_archivos.html",
  "5_pwa/5_index.html",
  "5_pwa/6_CtrlDivide.html",
  "5_pwa/7_agent.html",
  "5_pwa/8_regSw.html",
  "5_pwa/9_sw.html",
  "5_pwa/10_webmanifest.html",
  "5_pwa/11_estilos.html",
  "5_pwa/12_campo.html",
  "5_pwa/13_nav.html",
  "5_pwa/14_nav_css.html",
  "5_pwa/15_favicon.html",
  "5_pwa/16_icono256.html",
  "5_pwa/17_icono1024.html",
  "5_pwa/18_icono2048.html",
  "5_pwa/19_ayuda.html",
  "5_pwa/20_gps.html",
  "5_pwa/21_archivos.html",
  "5_pwa/22_README.html",
  "5_pwa/23_LICENSE.html",
  "5_pwa/index.html",
  "6_iot/cmp/ctrl-diapositiva.js",
  "6_iot/cmp/nav-local.js",
  "6_iot/img/casos_iot.svg",
  "6_iot/img/despliegue_iot.svg",
  "6_iot/img/entidades_iot.svg",
  "6_iot/img/nosql_iot.svg",
  "6_iot/src/init.js",
  "6_iot/src/LICENSE.html",
  "6_iot/2_contenido.html",
  "6_iot/3_casos.html",
  "6_iot/4_despliegue.html",
  "6_iot/5_er.html",
  "6_iot/6_no_rel.html",
  "6_iot/7_instrucciones.html",
  "6_iot/8_archivos.html",
  "6_iot/9_tipos.html",
  "6_iot/10_init.html",
  "6_iot/11_index.html",
  "6_iot/12_CtrlMovil.html",
  "6_iot/13_fabrica.html",
  "6_iot/14_tiposFire.html",
  "6_iot/15_util.html",
  "6_iot/16_footer.html",
  "6_iot/17_estilos.html",
  "6_iot/18_dispositivo.html",
  "6_iot/19_ResInt.html",
  "6_iot/20_utilIoT.html",
  "6_iot/21_CtrlDispositivo.html",
  "6_iot/22_ProxySalida.html",
  "6_iot/23_ProxyEntrada.html",
  "6_iot/24_ProxyHistorial.html",
  "6_iot/25_historial.html",
  "6_iot/26_CtrlHistorial.html",
  "6_iot/27_README.html",
  "6_iot/28_LICENSE.html",
  "6_iot/index.html",
  "7_esp8266/cmp/ctrl-diapositiva.js",
  "7_esp8266/cmp/nav-local.js",
  "7_esp8266/img/MiGet.png",
  "7_esp8266/img/MiPatch.png",
  "7_esp8266/img/MiPost.png",
  "7_esp8266/src/descarga.json",
  "7_esp8266/src/modifica.json",
  "7_esp8266/src/publica.json",
  "7_esp8266/2_contenido.html",
  "7_esp8266/3_blink.html",
  "7_esp8266/4_button.html",
  "7_esp8266/5_descarga.html",
  "7_esp8266/6_MiGet.html",
  "7_esp8266/7_modifica.html",
  "7_esp8266/8_MiPatch.html",
  "7_esp8266/9_publica.html",
  "7_esp8266/10_MiPost.html",
  "7_esp8266/index.html",
  "8_dispositivo/cmp/ctrl-diapositiva.js",
  "8_dispositivo/cmp/nav-local.js",
  "8_dispositivo/2_contenido.html",
  "8_dispositivo/3_archivos.html",
  "8_dispositivo/4_Dispositivo.html",
  "8_dispositivo/5_ResInt_h.html",
  "8_dispositivo/6_ResInt_c.html",
  "8_dispositivo/7_utilIoT_h.html",
  "8_dispositivo/8_utilIoT_c.html",
  "8_dispositivo/9_ProxySalida_h.html",
  "8_dispositivo/10_ProxySalida_c.html",
  "8_dispositivo/11_ProxyEntrada_h.html",
  "8_dispositivo/12_ProxyEntrada_c.html",
  "8_dispositivo/13_ProxyHistorial_h.html",
  "8_dispositivo/14_ProxyHistorial_c.html",
  "8_dispositivo/index.html",
  "cmp/base.js",
  "cmp/mi-footer.js",
  "cmp/mi-nav.js",
  "css/estilos.css",
  "css/gentium-book-basic-v11-latin-700.woff",
  "css/gentium-book-basic-v11-latin-700.woff2",
  "css/gentium-book-basic-v11-latin-700italic.woff",
  "css/gentium-book-basic-v11-latin-700italic.woff2",
  "css/gentium-book-basic-v11-latin-italic.woff",
  "css/gentium-book-basic-v11-latin-italic.woff2",
  "css/gentium-book-basic-v11-latin-regular.woff",
  "css/gentium-book-basic-v11-latin-regular.woff2",
  "css/gentium-book-basic.css",
  "css/material-icons.css",
  "css/MaterialIcons-Regular.codepoints",
  "css/MaterialIcons-Regular.ttf",
  "css/mi-footer.css",
  "css/ubuntu-mono-v10-latin-700.woff",
  "css/ubuntu-mono-v10-latin-700.woff2",
  "css/ubuntu-mono-v10-latin-700italic.woff",
  "css/ubuntu-mono-v10-latin-700italic.woff2",
  "css/ubuntu-mono-v10-latin-italic.woff",
  "css/ubuntu-mono-v10-latin-italic.woff2",
  "css/ubuntu-mono-v10-latin-regular.woff",
  "css/ubuntu-mono-v10-latin-regular.woff2",
  "css/ubuntu-mono.css",
  "css/ubuntu-v15-latin-700.woff",
  "css/ubuntu-v15-latin-700.woff2",
  "css/ubuntu-v15-latin-700italic.woff",
  "css/ubuntu-v15-latin-700italic.woff2",
  "css/ubuntu-v15-latin-italic.woff",
  "css/ubuntu-v15-latin-italic.woff2",
  "css/ubuntu-v15-latin-regular.woff",
  "css/ubuntu-v15-latin-regular.woff2",
  "css/ubuntu.css",
  "img/icono256.png",
  "img/icono1024.png",
  "img/icono2048.png",
  "js/registraServiceWorker.js",
  "js/title.js",
  "lib/comun.js",
  "lib/ctrl-diapositiva.css",
  "lib/CtrlDiapositiva.js",
  "lib/layout-cajon_shadow.js",
  "lib/layout-cajon.js",
  "lib/muestra-codigo_shadow.js",
  "lib/muestra-codigo.js",
  "lib/utilHtml.js",
  "2_sw.html",
  "favicon.ico",
  "index.html",
  "LICENSE",
  "manifest.json",
  "README.md",
  '/'
];

self.addEventListener("install", evt => {
  console.log("Service Worker instalado.");
  evt.waitUntil(cargaCache());
});

self.addEventListener("fetch", evt => {
  if (evt.request.method === "GET") {
    evt.respondWith(usaCache(evt));
  }
});

self.addEventListener("activate", () => console.log("Service Worker activo."));

async function cargaCache() {
  console.log("Intentando cargar cache: " + CACHE);
  const cache = await caches.open(CACHE);
  await cache.addAll(ARCHIVOS);
  console.log("Cache cargado: " + CACHE);
}

async function usaCache(evt) {
  const cache = await caches.open(CACHE);
  const response = await cache.match(evt.request, { ignoreSearch: true });
  if (response) {
    return response;
  } else {
    return fetch(evt.request);
  }
}